--UNION KOMUTU A KUME BILESKE B KUME'YI GOSTERIR
--DAHA ACIKLAYICI OLURSAK A TABLOSU ILE B TABLOSUNU KOMPLE BIRLESTIREREK GOSTERIR

--INTERSECT KOMUTU A KUME KESISIM B KUME'I GOSTERIR
--DAHA ACIKLAYICI OLURSAK A TABLOSU ILE B TABLOSUNUN ORTAK KISMINI GOSTERIR

--MINUS KOMUTU A KUME ZITTI B KUME'YI GOSTERIR
--DAHA ACIKLAYICI OLURSAK A TABLOSU ILE B TABLOSUNUN KESISMEYEN KISMINI VERIR

UNION : BILESKE - AYNI OLANLARI VERIR
UNION ALL : BILESKE - HEPSINI VERIR
INTERSECT : KESISIM - ORTAK OLANLARI VERIR
MINUS - ZIT - FARKLI - FARK


--ORNEKLER:>
--TABLO KOPYALAMA:
CREATE TABLE EMP2 AS SELECT * FROM EMP WHERE DEPTNO <> 30;

SELECT * FROM EMP2;

--UNION KOMUTU ORNEK:>
SELECT * FROM EMP 
UNION --UNION BILESKE KISMI GETIRIR ANCAK TEKRAR EDEN(HER IKI TABLODA DA OLAN) KAYITLARI BIR KEZ GETIRIR
SELECT * FROM EMP2;

--UNION ALL KOMUTU ORNEK:>
SELECT * FROM EMP 
UNION ALL --UNION BILESKE KISMI GETIRIR ANCAK TEKRAR EDEN(HER IKI TABLODA DA OLAN) KAYITLARI TEKRARLI OLARAK GETIRIR
SELECT * FROM EMP2;

--INTERSECT HER IKISINDEKI ORTAK OLANLARI GOSTERIR
SELECT * FROM EMP 
INTERSECT
SELECT * FROM EMP2;

--MINUS HER IKISINDEKI ZIT OLANLARI GOSTERIR. ARASINDAKI FARKI GOSTERIR
SELECT * FROM EMP 
INTERSECT
SELECT * FROM EMP2;

