--COALESC() FONKSIYONU
--ILK DEGER, NULL DEGILSE, ILK DEGERI DONDUR.
--ILK DEGER NULL'SA 1000 DONDUR.
SELECT
COALESCE(COMM + SAL, SAL, 1000) SALARY_
FROM EMP;


--DECODE() AND UNIQUE
--BIRINCI DEGER 10'A SATICI, 20'SE ALICI, HIC BIRI ISE 'BILINMIYOR'
SELECT
UNIQUE DEPTNO,--DISTINC GIBI BENZERSIZ OLANLARI ALIYOR.
DECODE(DEPTNO, 10, 'SATICI', 20, 'ALICI', 'BILINMIYOR')
FROM EMP;


--GREATEST() FONKSIYONU
--EN BUYUK OLANI VERIR
SELECT 
GREATEST('AHMET','MEHMET','VELI','DELI(HUSEYIN)') EN_BUYUK_AZAMI
FROM DUAL;

--LEAST() FONKSIYONU
--EN KUCUK OLANI VERIR
SELECT 
LEAST(110,250,0,10,44,780,3,1) EN_KUCUK_ASGARI
FROM DUAL;


--NVL() FONKSIYONU
--BIRINCI PARAMETRE NULL'SA DIGER PARAMETREYI DONDURUR
SELECT NVL(NULL,1) BIR, NVL(JOB ,5) FROM EMP;


--NVL2() FONKSIYONU
--BIRINCI BOS DEGILSE IKINCIYI, BOS SA IKINCIYI DONDURUR
SELECT
NVL2(COMM, COMM + SAL, SAL) SALARY 
FROM EMP;


--NULLIF() FONKSIYONU
--BIRINCI NULL'SA IKINCIYI DONDER.
--BIRINCI NULL DEGILSE KENDINI DONDER
SELECT E1.ENAME, E1.JOB, E2.JOB,
NULLIF(E1.JOB, E2.JOB) OLD_JOB
FROM EMP E1, EMP2 E2
WHERE E1.DEPTNO = E2.DEPTNO;

--SISTEM HAKKINDA BILGILER VERIR
Select sys_context('USERENV','SESSION_USER') Usemame,
Sys_context('USERENV', 'ISDBA') ISDBA,
sys_context('USERENV','HOST')  HOST,
sys_context('USERENV','INSTANCE') INSTANCE,
sys_context('USERENV','IP_ADDRESS')IP_ADDRESS,
sys_context('USERENV','DB_NAME') DB_NAME
FROM DUAL;
