--ISTATISTIKSEL FONKSIYONLAR HER SATIR YERINE SATIR GRUPLARINA DAYALI TEK DEGER DONDURUR.!
--AVG() FONKSIYONU ORTALAMALARI BULUR
SELECT
AVG(SAL) 
FROM EMP;

--ONEMLI SORU?
--SQL'DE ONDALIKLI SAYILAR 38 KARAKTERE KADAR HASSASIYET GOSTERIR.!
SELECT
ROUND(SUM(SAL), 2),
MAX(SAL),
MIN(SAL),
ROUND(STDDEV(SAL),2),
ROUND(VARIANCE(SAL),2),
COUNT(*)
FROM EMP;