--ALT SORGULAR

--ORTALAMAYI BULUR EMP TABLOSUNDAKI
SELECT
ROUND(AVG(SAL),0) ORTALAMA
FROM EMP;

--ALT SORGU KULLANIMI
--ORTALAMANIN ALTINDA KALANLAR
SELECT SAL FAKIR_MAAS, ENAME FROM EMP WHERE SAL < (SELECT AVG(SAL) FROM EMP);
SELECT * FROM EMP WHERE SAL < (SELECT AVG(SAL) FROM EMP);

--MAXIMUM(AZAMI) EN COK MAASI ALAN KISI
SELECT SAL ZENGIN_MAAS, ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);


--MINIMUM(ASGARI) EN AZ MAASI ALAN KISI
SELECT SAL FAKIR_MAAS, ENAME FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP);
SELECT * FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP);


--MINIMUM(ASGARI) EN AZ MAASI ALAN KISI VE MAXIMUM(AZAMI) EN COK MAASI ALAN KISI
SELECT
SAL MAAS,
MAX(SAL) ZENGIN_ADAMIN_MAASIDA_BEK_GOZEL_OLUR_HA, MIN(SAL) FAKIR_ADAM
FROM EMP
WHERE
SAL = (SELECT MIN(SAL) FROM EMP)
OR
SAL = (SELECT MAX(SAL) FROM EMP)
GROUP BY SAL
ORDER BY SAL DESC;

--2.
SELECT
SAL MAAS,
MAX(SAL) ZENGIN_ADAMIN_MAASIDA_BEK_GOZEL_OLUR_HA, MIN(SAL) FAKIR_ADAM
FROM DENEME
WHERE
SAL = (SELECT MIN(SAL) FROM DENEME)
OR
SAL = (SELECT MAX(SAL) FROM DENEME)
GROUP BY SAL
ORDER BY SAL DESC;


SELECT * FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP);

--DENEME TABLO OLUSTURDUK
CREATE TABLE DENEME(
    DID NUMBER,
    ENAME VARCHAR(20),
    SAL NUMBER(4,4)
);
ALTER TABLE DENEME MODIFY SAL NUMBER;
INSERT INTO DENEME(DID, ENAME, SAL) VALUES(1, 'HUSEYIN', 1000);
SELECT * FROM DENEME;




--ALT SORGULU TABLO OKUMALI JOIN CHALLENGE (-: (-: :-) :-)
SELECT
X.DEPTNO,
X.ENAME
FROM DEPT Y, (SELECT EMPNO, ENAME, DEPTNO FROM EMP) X
WHERE Y.DEPTNO = X.DEPTNO;


--__