--COMMIT: TRANSACTION KALICI OLARAK DB'E YANSIR.! (SULTAN ABDUL HAMIT HAN'IN MUHRU)
--ROLLBACK: YAPILAN ISLEM GERI ALINIR.!
--SAVEPOINT DAHA SONRA GERI ALINABILIR BIR ISLEM NOKTASI BELIRLENIR.!
--TRANSACTION CONTROL IFADELERI DML(INSERT - UPDATE - DELETE) ISLEMLERI ILE DB'DE YAPILAN DEGISIKLIKLERI YONETIR.


--TRANSACTION NEDIR?
--BIR TRANSACTION ORACLE'DE TEK BIR BIRIM OLARAK ELI ALINAN SQL IFADELERIDIR.!
--YA HEP YA HIC PRENSIBI ILE CALISIR. YA YAPILAN BUTUN DEGISIKLIKLER DB'E KANALI OLARAK YANSIR(COMMIT) YAHUT GECERSIZ KILINIR(ROLLBACK)
--DML(INSERT - UPDATE - DELETE) ISLEMLERININ SONUCLARI BIRER TRANSACTION'DUR.!
--DML ISLEMLERININ KALICI HALE GELMESI YAHUT GERI ALINMASI 4 TURLU OLABILIR.
--BUNLAR COMMIT - ROLLBACK - DDL(DATA DEFINITION LANGUAGE) KOMUTU VERILMESI YAHUT OTURUMUN NORMAL YOLLARLA SON BUMASI ILE OLUR.
--OTURUM DEVAM EDERKEN ELEKTRIGIN GITMESI VEYA CRASH OLMASI OTOMATIK OLARAK ROLLBACK YAPILMASINI SAGLAR.!

--DML KOMUTUNUN ARDINDAN DDL KOMUTU GIRILIRSE OTOMATIK COMMIT EDILIR.!

--COMMIT;
DESC EMP;
INSERT INTO EMP(EMPNO, ENAME, EMAIL)
VALUES(556, 'HUSEYIN', 'truncatecreate@gmail.com');
COMMIT; --EGER DML ISLEMINDEN SONRA COMMIT'LEMEZSEK DIGER OTURUMLAR DEGISIKLIGI GOREMEZLER.

--ROLBACK;
ROLLBACK; --YAPILAN DML ISLEMINI GECERSIZ KILAR / GERI ALIR. KALICI HALE GELMEZ.


INSERT INTO EMP(EMPNO, ENAME, EMAIL)
VALUES(556, 'HUSEYIN', 'truncatecreate@gmail.com');
SAVEPOINT A;


INSERT INTO EMP(EMPNO, ENAME, EMAIL)
VALUES(557, 'CUMALI', 'CUMALI@gmail.com');
SAVEPOINT B;


INSERT INTO EMP(EMPNO, ENAME, EMAIL)
VALUES(558, 'AHMET', 'AHMET@gmail.com');
SAVEPOINT C;
--BU NOKTADA SADECE ROLLBACK YAPARSAK BUTUN ISLEMLERI GERI ALIRIZ.
ROLLBACK TO B; --SADECE B KAYIT NOKTASINA GITTIK. SADECE O KISMA KADAR GERI ALINDI / GECERSIZ KILINDI.!












--__