--BUTUNLUK KISITLAMALARI TABLOLARA YANLIS BILGILERIN GIRILMESINI ENGELLEMEYI AMACLAYAN VERI BUTUNLUGU VERI ILISKISI GIBI KURALLAR BUTUNUDUR.
--BUTUNLUK KISITLAMALARINA IMKAN TANIYAN VERITABANLARINA "IVTYS(RDBMS)" DENIR.

--BUTUNLUK KISITLAMALARI SUNLARDIR:
--NOT NULL
CREATE TABLE BOLGELER(
    BNO NUMBER(3),
    BNAME VARCHAR(25),
    BAREA NUMBER(10, 2)
);
DESC BOLGELER;
DROP TABLE BOLGELER;

ALTER TABLE BOLGELER MODIFY BNO NUMBER(3);


--PRIMARY KEY
--PRIMARY KEY 1. KULLANIM
CREATE TABLE BOLGELER(
    BNO NUMBER(3) PRIMARY KEY,
    BNAME VARCHAR(25),
    BAREA NUMBER(10, 2)
);
--PRIMARY KEY 2. KULLANIM
CREATE TABLE BOLGELER(
    BNO NUMBER(3),
    BNAME VARCHAR(25),
    BAREA NUMBER(10, 2),
    CONSTRAINT PK_BNO PRIMARY KEY(BNO)
);
--PRIMARY KEY 3. KULLANIM
ALTER TABLE BOLGELER ADD CONSTRAINT PK_BNO PRIMARY KEY(BNO);
DESC BOLGELER;
--FOREING KEY 
--DIS ANAHTAR BASKA BIR TABLONUN PRIMARY KEY'INE YADA UNIQUE KEY'INE REFERANS VERMEK DEMEKTIR.
--FOREING KEY TANIMLANDIGINDA DIGER TABLONUN REFERANS VERILEN KOLONUNDA OLMAYAN DEGER FOREIGN KEY TANIMLANAN TABLONUN KOLONUNDA GIRILMEZ.
--FOREIGN KEY PARENT CHILD ILISKISIDIR. 
--TABLOYU OLUSTURMA ASAMASINDA FOREIGN KEY TANIMLAYABILIRIZ.!
--FOREIGN KEY PARAMETRELERI:
--1-) ON DELETE RESTRICT(DEFAULT) CHILD TABLODAN BILGI SILINMEDEN PARENT TABLODAN BILGI SILINMEYE IZIN VERMEZ.!
--2-) ON DELETE CASCADE PARENT TABLODAN KAYIT SILINDIGINDE CHILD TABLODANDA KAYIT OTOMATIK OLARAK SILINIR.
--3-) ON DELETE ACTIONS PARENT TABLODAN KAYIT SILINDIGINDE CHILD TABLODAKI KAYIT KALIR.(ORPHAN DATA).
CREATE TABLE SEHIRLER(
    BNO NUMBER(3),
    SNO NUMBER(3),
    POPUL NUMBER(8),
    POSTCODE NUMBER(10),
    CONSTRAINT FK_BNO FOREIGN KEY(BNO) REFERENCES BOLGELER(BNO)
);

--YALIN HALIYLE - ALTER ILE YAPILISI
DROP TABLE SEHIRLER;
CREATE TABLE SEHIRLER(
    BNO NUMBER(3),
    SNO NUMBER(3),
    POPUL NUMBER(8),
    POSTCODE NUMBER(10)
);
ALTER TABLE SEHIRLER ADD CONSTRAINT FK_BNO FOREIGN KEY(BNO) REFERENCES BOLGELER(BNO);


--CHECK
--CHECK CONSTRINTS ILE BAZI GIRILECEK DEGERLERI KISITLAYABILIRIZ.!

--ALTER ILE YAPILISI:
ALTER TABLE SEHIRLER ADD CONSTRAINT CK_SAL CHECK(SAL <=1499); --MAAS ICIN
ALTER TABLE SEHIRLER ADD CONSTRAINT CK_POSTCODE CHECK(POSTCODE >1000); --POSTA KODU ICIN

--YALIN HALDE YAPILISI:
CREATE TABLE SEHIRLER(
    BNO NUMBER(3),
    SNO NUMBER(3),
    POPUL NUMBER(8),
    POSTCODE NUMBER(10),
    CONSTRAINT CK_POSTCODE CHECK(POSTCODE >1000)
);

--UNIQUE
--UNIQUE KEY, PRIMARY KEY'E BENZERDIR. BASKA BIR TABLODAN UNIQUE KEY'E FOREIGN KEY TANIMLANABILIR.
--PRIMARY KEY ILE UNIQUE KEY ARASINDA IKI FARK VARDIR.
--BIR TABLODA SADECE BIR TANE PRIMARY KEY OLABILIR.!!!!  ||  UNIQUE KEY BIRDEN FAZLA OLABILIR.
--PRIMARY KEY NULL DEGER KABUL ETMEZ.  ||  UNIQUE KEY NULL DEGER KABUL EDER.
--ALTER EDERKEN
CREATE TABLE BOLGELER(
    BNO NUMBER(3),
    BNAME VARCHAR(25),
    BAREA NUMBER(10, 2),
    CONSTRAINT PK_BNO PRIMARY KEY(BNO),
    CONSTRAINT UQ_POSTCODE UNIQUE(POSTCODE)
);
ALTER TABLE SEHIRLER ADD CONSTRAINT UQ_POSTCODE UNIQUE(POSTCODE);
--ENABLE DISABLE
ALTER TABLE SEHIRLER DISABLE CONSTRAINT UQ_POSTCODE;
ALTER TABLE SEHIRLER ENABLE CONSTRAINT UQ_POSTCODE;


--CONSTRINTS ORNELER:
CREATE TABLE BOLGELER(
    BNO NUMBER(3),
    BNAME VARCHAR2(50) NOT NULL,
    BAREA NUMBER(10,2),
    CONSTRAINT PK_BNO PRIMARY KEY(BNO),
    CONSTRAINT CK_BAREA CHECK(BAREA != 00)
);
CREATE TABLE BOLGELER(
    BNO NUMBER(3),
    SNO NUMBER(3),
    POPUL NUMBER(10),
    POSTCODE NUMBER(5),
    CONSTRAINT PK_BNOSNO PRIMARY KEY(BNO, SNO),
    CONSTRAINT UQ_POSTCODE UNIQUE(POSTCODE),
    CONSTRAINT FK_BNO FOREIGN KEY(BNO) REFERENCES BOLGELER(BNO)
);
    






--__