--INDEXES:
--COMPOSITE INDEXES:
DESC EMP;
CREATE INDEX INDX_ENAME ON EMP(ENAME);

--BITMAP INDEX:
CREATE BITMAP INDEX BINDX_DEPTNO ON EMP(DEPTNO);

--FUNCTION INDEX:
CREATE INDEX FINDX_ENAME ON EMP(SAL + COMM);
DROP INDEX FINDX_ENAME;

--SAHIP OLUNAN INDEXLERI LISTELEMEK
SELECT * FROM USER_INDEXES;