-- BUILD IN FUNCTIONS
--HAZIR FONKSIYONLAR
SELECT ABS(90) FROM DUAL; --ABSOLUTE / MUTLAK DEGER
--SAYININ KENDISINI VERIR
--EKSI DEGER VERILIRSE ARTI HALINI VERIR

SELECT ABS(-90) FROM DUAL;
--EKSI -90'I VERIRSEN +90'I ALIRSIN.


--ACOS() FONKSIYONU:>
--ACOS() FONKSIYONU -1 ILA +1 ARASINDA BIR DEGER ALIR PARAMETRE OLARAK
--ACOS() FONKSIYONUNA -1 ILA +1 ARASI HARICINDE BIR DEGER VERIRSEK HATA ALIRIZ
--ACOS() FONKSIYONU RADYAN BIR DEGER DONDURUR

SELECT ACOS(9) FROM DUAL; --HATA PATLADIK!!!

SELECT ACOS(1/2) FROM DUAL; --ALDIGIMIZ DEGER RADYAN BIR DEGERDIR

SELECT CEIL(9.1) FROM DUAL;
--VERILEN SAYIYI USTTEN / YUKARIYA TAMSAYIYA YUVARLAR

SELECT CEIL(5.0000000001) FROM DUAL;
--VERILEN SAYIYI USTTEN / YUKARIYA TAMSAYIYA YUVARLAR

SELECT FLOOR(9.1) FROM DUAL;
--VERILEN SAYIYI ALTTAN / ASAGIYA TAMSAYIYA YUVARLAR

SELECT FLOOR(9.000000009) FROM DUAL;
--VERILEN SAYIYI ALTTAN / ASAGIYA TAMSAYIYA YUVARLAR


--MOD() FONKSIYONU 
--GIRILEN IKI SAYIDAN BIRINCISININ/IKINCISINE BOLUMUNU VERIR
SELECT MOD(10,2) FROM DUAL; --10 2'YE TAM BOLUNEBILIYOR!
SELECT MOD(10,3) FROM DUAL; --10 2'YE TAM BOLUNEMIYOR!
--0 KALDIYSA TAM BOLUNEBILIR!!!
--1 KALDIYSA TAM BOLUNEMEZ!!!


--POWER() FONKSIYONU
--GIRILEN IKI SAYIDAN BIRINCI UZERI IKINCIYI VERIR
SELECT POWER(10,2) FROM DUAL;

--EXP() FONSIYONU | TEK PARAMETRELI
--e SAYISI PI SAYISI GIBI SABIT BIR SAYIDIR
--GIRILEN SAYININ e UZERI GIRILEN SAYIYI DONDURUR
SELECT EXP(1) FROM DUAL;
SELECT POWER(2.71,2) FROM DUAL;

--LN() FONKSIYONU
SELECT LN(3) FROM DUAL;
--LOG() FONKSIYONU
SELECT LOG(3,5) FROM DUAL;


--ROUND(M,N) FONKSIYONU
--YUVARLAMA FONKSIYONUDUR
--M SAYISINI N DIGIT KADAR YUVARLAR
SELECT ROUND(6.4573,2), ROUND(12.56), ROUND(173.557,-2) FROM DUAL;
--RESULT: 6.46, 13, 200
--EGER -2 PARAMETRESI GECERSEK TAM SAYI KISMINI YUVARLAMIS OLURUZ.!

--TRUNC(M,N) M SAYISININ ONDALIKLI KISMINDAN N KADAR KESER ATAR.
SELECT TRUNC(10.478,2) FROM DUAL;

--SQRT() SAYININ KARE KOKUNU BULUR
SELECT SQRT(2) FROM DUAL;








