--SYSDATE: FORMATLAMAYA BAGLI OLARAK OTURUMUN'IN TARIHINI DONDURUR. ISLETIM SISTEMININ TARIHINI VERIR.
--CURRENT_DATE: OTURUMUN GREGORIAN TAKVIMINE GORE TARIH DILIMINDEKI GECERLI TARIHI DONDURUR. VERITABANININ TARIHINI DONDURUR.
--SYSTIMESTAMP: ZAMAN DAMGASI. VERITABANININ SYSTEM TARIHINI VE ZAMANINI DONDURUR.
SELECT
SYSDATE SYSDATE1,
SYSTIMESTAMP SYSTIMESTAMP1,
CURRENT_DATE CURRENT_DATE1
FROM DUAL;


--
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MON/YYYY HH24:MI:SS';

--
SELECT 
TO_CHAR(SYSDATE, 'DD/MM/YYYY') TAR1
FROM DUAL;


--

SELECT SESSIONTIMEZONE BOLGE_ZAMAN_DAMGASI, TO_CHAR(CURRENT_DATE, 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;


--DATE FORMAT PREFIX
SELECT SYSDATE, TO_CHAR(SYSDATE,'D') FROM DUAL; --D HAFTANIN O ANKI GUNUNU VERIR | ORNEK PAZARTESI 1. GUNDUR.!

SELECT SYSDATE, TO_CHAR(SYSDATE,'DD') FROM DUAL; --D AYDIN O ANKI GUNUNU VERIR | ORNEK KASIMIN 6. GUNUNDEYIZ.!

SELECT SYSDATE, TO_CHAR(SYSDATE,'DDD') FROM DUAL; --D YILIN O ANKI GUNUNU VERIR

SELECT SYSDATE, TO_CHAR(SYSDATE,'W') FROM DUAL; --D AYIN O ANKI HAFTASINI VERIR

SELECT SYSDATE, TO_CHAR(SYSDATE,'WW') FROM DUAL; --D AYIN O ANKI HAFTASINI VERIR

SELECT HIREDATE, REPLACE(REPLACE(INITCAP(TO_CHAR(HIREDATE,'day, ddth month, yyyy')),'st','.'),'md','.') FROM EMP;


--TO_DATE() GIRILEN STRING FORMATITARIH FORMATINA CEVIRIR
SELECT
TO_DATE('01-may-2022','dd-mon-yyyy') STATIC,
TO_DATE(TO_CHAR(SYSDATE)) SYSTEMDATE_
FROM DUAL;
--TO_CHAR() VE TO_DATE() BIRLIKTE KULLANIMI
SELECT
TO_DATE('29/10/1923','DD/MM/YYYY') YIL1923,
TO_DATE('29/EKÝ/1923', 'DD/MM/YYYY') YIL1923,
TO_CHAR(TO_DATE('29/EKI/1923', 'DD/MM/YYYY'),'DAY') GUN,
ROUND(SYSDATE - TO_DATE('29/10/1923','DD/MM/YYYY'),2) GUN_FARKI_
FROM DUAL;

--ADD_MONTHS() KULLANIMI
SELECT
ADD_MONTHS(SYSDATE,4) DORT_AY_SONRASI,
ADD_MONTHS(SYSDATE,-4) DORT_AY_ONCESI
FROM DUAL;


--ROUND() VE MONTHS_BETWEEN() BIRLIKTE KULLANIMI
SELECT
ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE('11/09/1994', 'DD/MM/YYYY')),2) KAC_AY_YASAMISIM, --AY FARKI
TO_CHAR(ROUND(((SYSDATE) - TO_DATE('11/09/1994', 'DD/MM/YYYY')),0)) KAC_GUN_YASAMISIM --TOPLAM YASADIGIM GUNU VERIR. BU KOMUT CALISTIGINDA BEN 10285 GUNLUKMUSUM
FROM DUAL;





--
SELECT 
SYSDATE - TO_DATE('03-may-1944','dd-mon-yyyy') FARK_1944
FROM DUAL;









--__