--ROLE BIRTAKIM YETKILERIN TOPLANDIGI GRUPLARDIR.
--KULLANICILARIN NESNELER UZERINDE DOGRUDAN YETKILENDIRILMESI VERI TABANINI BIR SURE SONRA YONETILEMEZ HALE GETIRIR.
--O YUZDEN YETKILER GRUPLANDIRILMALI VE ROLLERE VERILMELIDIR.
--KULLANICILARA YETKILER BU ROLLER UZERINDEN VERILMELIDIR.
SHOW USER;

--CREATE ROLE - ROL OLUSTURMA
CREATE ROLE S1_ROLE; --BIR TANE ROLE OLUSTURDUK.

GRANT SELECT, INSERT ON EMP TO SI_ROLE; --VAR OLAN BIR ROLE EMP TABLOSU UZERNDE SELECT VE INSERT YETKILERI VERDIK.
GRANT SELECT, INSERT ON DEPT TO SI_ROLE; --VAR OLAN BIR ROLE DEPT TABLOSU UZERNDE SELECT VE INSERT YETKILERI VERDIK.

GRANT SI_ROLE TO AHMET;
GRANT SI_ROLE TO MEHMET;
GRANT SI_ROLE TO CUMALI;
--3'UDE EMP VE DEPT TABLOLARI UZERINDE AYNI YETKIYE SAHIP.

--ROLE'YI DROP ETME.!
DROP ROLE SI_ROLE;


--KIMLERE HANGI YETKI VERILMIS ONU GOSTERIR
SELECT * FROM USER_TAB_PRIVS_MADE;

--KIM BANA NE YETKI VERMIS ONU GORUYORUM.
SELECT * FROM USER_TAB_PRIVS_RECD;

--BEN HANGI KOLON UZERINDE BASKALARINA HANGI YETKILERI VERMISIM ONU GOSTERIR.!
SELECT * FROM USER_COL_PRIVS_MADE;












--__

