--VIEW'LER MANTIKSAL TABLOLARDIR.
--VERITABANINDA FIZIKSEL OLRAK TUTULMAZLAR SADECE SELECT SORGUSUNUN SONUDUR.
--BU SORGUNUN SONUCU JOINLER ILE BIRLESTIRILMIS TABLOLARIN SONUCUNDAN OLUSUR.
--BIR VEYA BIRDEN FAZLA VIEW UZERINDEN YADA BIR VEYA BIRDEN FAZLA TABLO UZERINDEN YENI VIEW'LER TANIMLANABILIRLER.
--CREATING VIEWS:
--EMP VE DEPT TABLOLARI UZERINDEN BIR VIEW OLUSTURALIM.
--RAPORDAKI KOLONLAR
/*
ILNO,
ILISMI,
ILCEISMI,
ILCE_SAYISI
*/
DESC ILLER;
DESC ILCELER;

SELECT IL_NO, ISIM, (SELECT COUNT(*) FROM ILCELER A WHERE A.IL_NO = B.IL_NO) TOPLAM_SATIR FROM ILLER B;

SELECT * FROM ILLER;
SELECT * FROM ILCELER;
--VIEW OLSUTURMA
CREATE OR REPLACE VIEW WILLICE(
    IL_MI,
    IL_NO,
    ILISMI,
    ILCEISMI,
    ILCE_SAYISI
)
AS
SELECT 
    1,
    IL_NO ILNO,
    ISIM ILSIMI,
    NULL ILCEISMI,
    (SELECT COUNT(*) FROM ILCELER B WHERE B.IL_NO = A.IL_NO) ILCE_SAYISI
FROM ILLER A
UNION
SELECT 
    0,
    NULL ILNO,
    NULL ILISMI,
    ISIM,
    NULL
FROM ILCELER;

DESC WILLICE;
SELECT 
    DECODE(IL_MI, 1, IL_NO, 0, NULL),
    ILISMI,
    ILCEISMI,
    ILCE_SAYISI
FROM WILLICE;

SHOW USER;

CREATE OR REPLACE VIEW EMP_DEPT_JOIN
AS
SELECT E.DEPTNO, E.ENAME, E.SAL, D.LOC, D.DNAME FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM EMP_DEPT_JOIN;

SELECT * FROM EMP;
SELECT * FROM DEPT;

DROP VIEW EMP_DEPT_JOIN;












--__