--SEQUENCES'LER SAYI URETECLERIDIR.
--OZELLIKLE PRIMARY KEY VE UNIQUE KEY ALANLARININ DEGERLERI ICIN KULLANILIRLAR.
--ORN 1:
CREATE SEQUENCE SEQ_SIPARIS
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100
CYCLE
CACHE 20;

--ORN 2:
CREATE SEQUENCE SEQ_SIPARIS
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

SELECT SEQ_SIPARIS.NEXTVAL FROM DUAL;
SELECT SEQ_SIPARIS.CURRVAL FROM DUAL;

CREATE TABLE SIPARIS(
SIPID NUMBER,
PRODUCT VARCHAR2(12),
MIKTAR NUMBER
);
INSERT INTO SIPARIS
VALUES(SEQ_SIPARIS.NEXTVAL, 'KALEM',300);
SELECT * FROM SIPARIS;

--ALTER ETME
ALTER SEQUENCE SEQ_SIPARIS MAXVALUE 30000;

--KULLANCIYA AIT NESNELER
SELECT * FROM USER_TABLES;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM USER_VIEWS;

DROP SEQUENCE SEQ_SIPARIS;
