--SYNONYMS
--SYNONYMLER NESNE ICIN TAKMA ADLARDIR.
--IKI TIP SYNONIM VARDIR.

--PUBLIC SYNONIM
--ILGILI NESNEYE SCHEMA ISMI VERMEDEN ULASILABILIR.

--PRIVATE SYNONYM
--ILGILI NESNEYE SCHEMA ISMI VEREREK ULASILABILIR.

--PRIVATE SYNONYM OLUSTURALIM
CREATE PUBLIC SYNONYM SYN0_EMP FOR EMP;
CREATE SYNONYM SYN1_EMP FOR EMP; --EMP TABLOSUNA 'SYN1_EMP' TAKMA ISMINI VERDIK. LAKAP TAKTIK.
DROP SYNONYM SYN1_EMP; --PRIVATE SYNONYM'I SILDIK. PUBLIC OLARAK TANIMLANAN BIR SYNONYM'LERI GOREMEYIZ.
--PUBLIC SYNONYM'LERI GORMEK ICIN SORGU:
SELECT * FROM ALL_SYNONYMS WHERE TABLE_OWNER = 'HUSEYIN';

SELECT * FROM HUSEYIN.SYN1_EMP;
SHOW USER;

GRANT CREATE SYNONYM TO HUSEYIN; --DBA YETKILI BIR KISI HUSEYIN'E CREATE SYNONYM YETKISI VERDI. TAKMA AD OLUSTURMA YETKISI VERDI.
GRANT CREATE PUBLIC SYNONYM TO HUSEYIN; --DBA YETKILI BIR KISI HUSEYIN'E CREATE SYNONYM YETKISI VERDI. TAKMA AD OLUSTURMA YETKISI VERDI.

SELECT * FROM PUBLIC.SYN0_EMP;
