--LOWER()
SELECT LOWER('HUSEYIN') FROM DUAL; --KUCUK HARFE CEVIRIR.!

SELECT UPPER('merhaba') FROM DUAL; --BUYUK HARFE CEVIRIR.!

SELECT INITCAP(LOWER(UPPER('huseyýn aydýn'))) FROM DUAL; --GIRILEN DEGERIN ILK HARINI BUYUK HALE GETIRIR

SELECT LENGTH('HELLO') FROM DUAL; --HELLO STRING IFADESININ UZUNLUGUNU VERIR.!

SELECT SUBSTR('LENOVO Y510P',5,2) FROM DUAL; --5. KARAKTERDEN BASLAYIP 2 TANE KES ANLAMINDADIR.

SELECT INSTR('MACBOOK PRO','R')INSTR,
SUBSTR('MONSTER',-3,1) SUBSTR
FROM DUAL; --SOLDAN ARAMA YAPAR. R KACINCI INDEX'DEYSE ONU BULUR.

SELECT
INSTR('HUSEYIN AAA U BBB','U',1,2), --STRING'IN ICINDE U HARFI 2. KEZ HANGI INDEX'DE GECIYOR? ONUN SQL KODU.!
INSTR('YASIN YASIN','Y',-1,2) --STRING'IN ICINDE U HARFI 2. KEZ HANGI INDEX'DE GECIYOR ONU TERSTEN SAYARAK BULUR. SQL KODU.!
FROM DUAL;

SELECT REPLACE('ORACLE aaa', 'R', 'x') FROM DUAL; --R KARAKTERINI x ILE DEGISTIR

--SIFRELEME TRANSLATE ILE.
--HUSEYIN STRING'INI ILGILI UYUSAN KARAKTERLERI SON PARAMETREDEKI KARSILIKLARINA CEVIRIR.!
SELECT 
TRANSLATE('HUSEYIN',
'ABCÇDEFGÐHIÝJKLMNOÖPRSÞTUÜVYZabcçdefgðhýijklmnoöprsþtuüvyz',
'a!bcç)ÐHI(ÝJ+dÜfgnoöpð=|}]!!"[{½$#£hýijklmnoöprsþtuüvyzABCÇDEFGÐHIÝJKLMNOÖPRSÞTUÜVYZ') CRYPTE_KRIPTO
FROM DUAL;


--RPAD() - LPAD() FONKSIYONLARI
SELECT 
RPAD(JOB, 15,'*') JOB_RIGHT_STARTS,--SAGDAN 15 KARAKTER * ATAR
LPAD(JOB,15,'-') JOB_LEFT_LINE--SOLDAN 15 KARAKTER - ATAR
FROM EMP;


--LTRIM() RTRIM() FONKSIYONLARI
SELECT
RTRIM('ORACLE  ') ORACLE_SAGDAN_TRIMLENMIS_HALI,
LTRIM('  ORACLE') ORACLE_SOLDAN_TRIMLENMIS_HALI
FROM DUAL;

SELECT TRIM(0 FROM '00000011500005889900074629000000000') FROM DUAL;
--ICERIDEKI 0'LAR HARIC SOL VE SAG'DAKI 0'LARI TEMIZLER!

--CONCAT() FONKSIYONU BIRLESTIRME ICIN KULLANILIR
SELECT 
CONCAT(CONCAT(ENAME, ' IS A '),JOB) BIRINCI,
ENAME || ' IS A ' || JOB IKINCI
FROM EMP;
--RESULT: ADI IS A ISI SEKLINDE :> HUSEYIN IS A MANAGER
















--